### ISSUE TITLE
WalleePaymentSdk sdk has same name as WalleePaymentSdk class and when making custom swift framework for BindingLibrary in .NET, type conflicts appear when compiling swift interface

### ISSUE THREAD

**Issue by RobertCiurea** [wallee-payment/ios-mobile-sdk-spec#1]
<img width="1281" alt="Screenshot 2024-08-06 at 16 51 41" src="https://github.com/user-attachments/assets/1d83716a-fe21-4ca4-92f3-072c30776bca">

//
//  WalleeProxy.swift
//  WalleeProxy
//
//  Created by Robert Ciurea on 06.08.2024.
//

import Foundation;
import UIKit;
import CryptoKit;
import AlertToast;
import SwiftUI;
import Alamofire;

//import class WalleePaymentSdk.WalleePaymentSdk
import protocol WalleePaymentSdk.WalleePaymentResultObserver
//import struct WalleePaymentSdk.PaymentResult

struct Toast: Equatable {
    var shouldShow: Bool
    var type: AlertToast.AlertType
    var title: String?
}

@objc(WalleeProxy)
public class WalleeProxy : NSObject, ObservableObject, WalleePaymentSdk.WalleePaymentResultObserver {
    var toast: Toast = Toast(shouldShow: false, type: .complete(Color.green), title: nil);
    var result: String = "";
    var wallee: WalleePaymentSdk?;
    
    public func paymentResult(paymentResultMessage: PaymentResult) {
        self.toast = Toast(shouldShow: true, type: paymentResultMessage.code == .COMPLETED ? .complete(Color.green) : .error(Color.red), title: paymentResultMessage.code.rawValue)
        self.result = paymentResultMessage.code.rawValue
            
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            self.toast = Toast(shouldShow: false, type: .complete(Color.green))
        }
    }
    
    @objc
    public func onOpenWalleeSdkPress(token: String){
        wallee = WalleePaymentSdk(eventObserver: self)
        guard let wallee = wallee else { return }
        self.toast = Toast(shouldShow: true, type: .loading)
        wallee.launchPayment(token: token, isSwiftUI: true)
    }
}

**Comment by NetPumi2** [comment]
can you provide us with more info? or what exactly are you trying to do?

**Comment by RobertCiurea** [comment]
I created a Framework project in swift

I wrote the code in swift for a proxy that should use the WallePaymentSdk


I tried to build so that I could generate the swift interface file

It crashes as the message in the photo

**Comment by RobertCiurea** [comment]
I am trying to make a Binding Library for a NET iOS application

**Comment by NetPumi2** [comment]
do you mean [.NET MAUI](https://dotnet.microsoft.com/en-us/apps/mobile)?... 
here is our implementation of this SDK in a real app maybe that could help:
https://github.com/wallee-payment/ios-sdk-demo-app

**Comment by RobertCiurea** [comment]
This is an implementation in swift, I am trying to implement the iOS sdk in a .NET project using a binding library. I figured how to do this after a while.  The problem was the fact that in the iOS sdk you implemented the WalleePaymentSdk framework, but you also named the class in the framework also WalleePaymentSdk and that generated a conflict when trying to generate Objective-C header from swift implementation in order to then generate C# header that can be used in a .NET project. I might suggest changing the name of the WalleePaymentSdk framework or the class that holds the main implementation of the sdk because the problem encountered is a common problem known in Swift regarding type conflicts and that is why it is not recommended to use the same name for a class as the name of the package that holds the sdk.

**Comment by NetPumi2** [comment]
I created task for us to fix this issue. Eventually we will modify our sdk but i can not tell you when.

**Comment by RobertCiurea** [comment]
Hello, can you provide a guide for creating a .NET iOS binding library for usage in a .NET iOS project? The classic method that is provided by Microsoft is not working because the walleepayment sdk for iOS does not provide classes and methods that can be exported in Objective-C in order to use the sharpie tool and generate the mapper for the native implementations.
